#
# Config for https://github.com/robb-j/akita
# -> A CLI for testing web sockets
#

url: ws://localhost:3000

messages:
  hello:
    type: echo
    body: Wazzup!

  viewHome:
    type: page_view
    path: /

  viewAbout:
    type: page_view
    path: /about

  viewProject:
    type: page_view
    path: /project/5c80fafc339c9d6d52b9529d

  linkClick:
    type: project_action
    project: 5c80fafc339c9d6d52b9529d
    link: mailto://geoff.testington@ncl.ac.uk
