#
# A GitLab CI file to build a docker image on push when the commit is tagged
# NOTE - Tags aren't pushed by default, you can `git push --tags` each time
#        or `git config --global push.followTags true`
#

image: robbj/ci:vault-1.0.2

services:
  - docker:dind

build:
  tags:
    - dind
  only:
    - tags
  script:
    - ls
    - pwd
    - ls /
    - ash /vault-docker-login.sh
    - IMAGE=openlab/catalyst-api:`echo $CI_COMMIT_TAG | sed 's/^v//'`
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE
