#
# A docker compose file to spin up a redis and put projects into it
# Used for development
#

version: '3'

services:
  # A data store for projects, lightweight and stored in memory
  redis:
    image: redis:4-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  # A mongo database for analytics
  mongo:
    image: mongo:3.6-stretch
    restart: unless-stopped
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    #   MONGO_INITDB_DATABASE: catalyst

  # Run the scraper once at startup
  one-time-scraper:
    image: ghcr.io/digitalinteraction/catalyst-trello-scraper
    env_file: .env
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
    command: fetch --verbose
